In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('/Users/shen-pc/Desktop/WORK/ITS/data/data_merge.csv',index_col='id')
data

body  \
id                                                        
0     已知直角三角形的两条直角边长分别是$6$，$ \sqrt{10} $，则斜边长为（$\:\:...   
1                                      $-3.782(\:\:\:)$   
2     如图，$ \triangle ABC$中，$B ^\prime $、$C ^\prime $...   
3     有一种投球游戏，将球投入下图所示的阴影区域记为“投中”，且投中一次得$20$分$.$狗蛋儿投...   
4                     解方程$5(3x-1)-2(x-1)=49$，得$x=$____.   
5     若定义：$f(a,b)=(-a,b)$，$g(m,n)=(-n,m)$ 例如：$f(1,2)...   
6     关于$x$的一元二次方程$x^2+2x-(k-1)=0$的根的情况，下列说法正确的是（$\:...   
7        一次函数$y=-3x-2$的图象向右平移$3$个单位后，新图象的解析式为（$\:\:\:$）   
8     关于$x$的一元二次方程$3x^2-4x+(2a+1)=0$的根的情况，下列说法正确的是（$...   
9     在四边形$ABCD$中， $ \angle B= \angle D=90 ^\circ $ ...   
10    关于$x$的一元二次方程$x^2-2(m+1)x+m^2-7=0$的根的情况，下列说法正确的...   
11    一个正数$x$的两个平方根分别为$5+a$和$3a-1$，则$a=$____；$x=$___...   
12    在$直角三角形 ABC$中，$ \angle C=90 ^\circ $，$ \angle ...   
13                     已知$a-b=3$，$ab=3$，则$(a+b)^2=$____   
14    用配方法解关于$x$的一元二次方程  $x^2+2mx-n=0(n+m^2 \geqslan...   
15    田豆花同学放学后从学校门口走路到公交站台，先坐公交到小区附近的站点，下公交车后遇见邻居聊了两...   
16                    $ \sqrt {5^3 \times 45} =$____$.$   
17    已知方程$x^2+2x-1=0$的两根分别是$x_1$，$x_2$，则$\frac{1}{x...   
18    计算： $\frac{1}{\sqrt {5}+1}$$ +$$ \frac{1}{\sqr...   
19    如果以每月生产$180$个零件为准，超过的零件数记作正数，不足的零件数记作负数，那么$1$月...   
20    计算：$ \frac{1}{\sqrt {6}+1}$$ +$$\frac{1}{\sqrt...   
21    分解因式$3x^{3n+1}y^{m-1}z-6x^{3n+2}y^m=$____（$\:\...   
22    关于$x$的一元二次方程$-2x^2-4(a+1)x-(2a^2+1)=0$的根的情况，下列...   
23    如图，$AD$是$ \triangle ABC$的中线，$E$、$F$分别在$AB$，$AC...   
24              单项式$- \frac{2x^2 y }{3} $的系数和次数之积是____.   
25                   单项式$-\frac{3x^2}{4}$的系数和次数之积是____.   
26    如图，$AD$、$BE$、$CF$是 $ \triangle ABC$的三条角平分线，求$ ...   
27    分解因式$6a^{x-2}b^{y+1}-2a^{x+1}b^y c=$____（$\:\:...   
28                    直线$y=4x+3$关于原点对称的直线$l$的解析式为  （  ）   
29                  一组数据：$12$，$18$，$10$，$20$的方差是____$.$   
...                                                 ...   
7023         已知抛物线顶点坐标以及另一点坐标，可设____求二次函数的解析式（$\:\:\:$）   
7024  下列各组判断中，正确的是$(\:\:\:)$  ①若$|x|>|y|$，则一定有$x>y$ ...   
7025  下列各组判断中，正确的是$(\:\:\:)$  ①若$|x|=|y|$，则一定有$x=y$或...   
7026  下列各组判断中，正确的是$(\:\:\:)$  ①若$|a|=b$，则一定有$a=b$   ...   
7027  下列各组判断中，正确的是$(\:\:\:)$  ①若$|m|=|n|$，则一定有$m=n$ ...   
7028  下列各组判断中，正确的是$(\:\:\:)$  ①若$|a|<|b|$，则一定有$a<b$ ...   
7029                       已知$|x-1|=3$，则$x$的值为$4$或____.   
7030                       已知$|x-4|=2$，则$x$的值为$6$或____.   
7031                       已知$|m-3|=1$，则$m$的值为$4$或____.   
7032  已知：$a$、$b$都是非$0$有理数，且满足$|ab|=-ab$，则$ \frac{a}{...   
7033  已知：$a$、$b$都是非$0$有理数，且满足$a+b=0$，则$ \frac{a}{|a|...   
7034  已知：$a$、$b$都是非$0$有理数，且满足$|ab|=-ab$，则$ \frac{a}{...   
7035  已知：$a$、$b$都是非$0$有理数，且满足$a+b=0$，则$ \frac{|a|}{a...   
7036  已知：$a$、$b$都是非$0$有理数，且满足$a+b=0$，则$ \frac{a}{|a|...   
7037           计算$(- \frac{1}{8} )+(-3.375)+(-2)=$____.   
7038  二次函数一般式$y=二次函数的ax^2+二次函数的bx+二次函数的c(a \ne 0)$中，...   
7039  二次函数一般式$y=二次函数的ax^2+二次函数的bx+二次函数的c(a \ne 0)$中，...   
7040  二次函数一般式$y=二次函数的ax^2+二次函数的bx+二次函数的c(a \ne 0)$中，...   
7041  下列说法 错误 的是$(\:\:\:)$  ①顺次连接对角线相等的四边形的各边中点所得四边形...   
7042  如图，能判定四边形$ABCD$为平行四边形的条件是$(\:\:\:)$   ①$AB//CD...   
7043  四边形$ABCD$中，对角线$AC$、$BD$相交于点$O$，下列条件 不能 判定这个四边形...   
7044        直线$y=-3x+4$与直线$y=(1-2k)x-3$互相垂直，则$k=$____（）   
7045        直线$y=-2x+5$与直线$y=(2-k)x+3$互相垂直，则$k=$____ （）   
7046        直线$y=3x-4$与直线$y=(1-2k)x+3$互相垂直，则$k=$____ （）   
7047        直线$y=2x-3$与直线$y=(2k-1)x-1$互相垂直，则$k=$____ （）   
7048  已知：如图，点$D$，$E$分别在$AC$和$AB$上，$CE$平分$\angle ACB$...   
7049  已知：如图，$\angle BAD=\angle BCD$，$\angle 1=\angle...   
7050  已知：如图，点$D$，$E$分别在$AC$和$AB$上，$CE$平分$\angle ACB$...   
7051  已知：如图，$BC$平分$\angle ACD$，$\angle 1=\angle B.$求...   
7052  已知：如图，$\angle C=70 ^\circ$，$AE$平分$\angle BAC$交...   

                                               explains  \
id                                                        
0     {"{\"body\": \"斜边长$= \\\\sqrt{6 ^2+( \\\\sqrt{...   
1     {"{\"body\": \"$-3.782$符号为负,是负数 \\n又是有限小数,是有理数...   
2     {"{\"body\": \"$ \\\\because \\\\angle CC ^\\\...   
3     {"{\"body\": \"狗蛋儿投掷$5$次的位置，即图中 

merge:'goal_name,subsection,chapter,section'

In [14]:
yls = []
for i in range(len(data)):
    if data['merge'][i].split(',')[2] == '有理数':
        yls.append(data.iloc[i])
yls

[body                                         $-3.782(\:\:\:)$
 explains    {"{\"body\": \"$-3.782$符号为负,是负数 \\n又是有限小数,是有理数...
 merge                                        数的分类,有理数,有理数,有理数
 Name: 1, dtype: object,
 body        如果以每月生产$180$个零件为准，超过的零件数记作正数，不足的零件数记作负数，那么$1$月...
 explains    {"{\"body\": \"“超过”与“不足”是以每月生产$180$个零件为准 \\n$ ...
 merge                                正负数的实际意义,正数和负数,有理数,正数和负数
 Name: 19, dtype: object,
 body               除以一个不等于$0$的数，等于乘以这个数的倒数.这一法则可表示成$(\:\:\:)$
 explains    {"{\"body\": \"有理数除法法则可以表示成：$p \\\\div q=p \\\...
 merge                               有理数的除法,有理数的除法,有理数,有理数的乘除法
 Name: 47, dtype: object,
 body        已知一种运算$P \triangle Q= \frac{P+Q}{3} $，则$1 \tri...
 explains    {"{\"body\": \"$ \\\\because $新运算的规则是：$P \\\\t...
 merge                                     定义新运算,乘方,有理数,有理数的乘方
 Name: 56, dtype: object,
 body                      计算$-3.6+(- \frac{1}{2})+(-3)=$____.
 explains    {"{\"body\": \"$\\\\:\\\\:\\\\:\\\\:-3.6+(- \\...
 merge         

In [18]:
yls_df = pd.DataFrame(yls)

In [33]:
yls_df[['goal_name','subsection','chapter','section']] = yls_df['merge'].str.split(',',expand=True)

In [59]:
yls_df

body  \
1                                      $-3.782(\:\:\:)$   
19    如果以每月生产$180$个零件为准，超过的零件数记作正数，不足的零件数记作负数，那么$1$月...   
47           除以一个不等于$0$的数，等于乘以这个数的倒数.这一法则可表示成$(\:\:\:)$   
56    已知一种运算$P \triangle Q= \frac{P+Q}{3} $，则$1 \tri...   
73                  计算$-3.6+(- \frac{1}{2})+(-3)=$____.   
105                          若$|a|+a=0$，则$a$是$(\:\:\:)$   
111                计算$-1.2+(- \frac{1}{5} )+(-5)=$____.   
134   仔细思考以下各对量： ①胜二局与负三局 ②气温上升$3$℃与气温下降$3$℃ ③盈利$5$万...   
148   如果$6\text{m}$表示水位升高$6\text{m}$，那么$-2\text{m}$表...   
167                       如果$a$，$b$互为相反数，则$a+b=$____$.$   
178   下列化简$(-3.6) \div (- \frac{3}{4} )$的过程正确的是$(\:\...   
185   下列化简$(-2.4) \div (- \frac{3}{8} )$的过程正确的是$(\:\...   
264                             在数轴上，原点及原点右边的点表示的数是====   
278   $-10^2 \div  \frac{1}{2}  \times  \frac{2}{5} ...   
285   用科学记数法把$320\:000$写成$a \times 10^n$，其中$a$是____，...   
300                $- 10\:140\:000$可用科学记数法表示为$(\:\:\:)$   
306                                $a-1$的相反数是$(\:\:\:)$   
318                    如图，在数轴上点$M$表示的数可能是 $(\:\:\:)$      
323   $1.75 \times (- \frac{3}{5})  \div (- \frac{14...   
325                         下列用科学记数法表示的数，正确的是$(\:\:\:)$   
331   $-0.6 \div (- \frac{8}{7} ) \div \frac{7}{12} ...   
347   用$ \odot $定义新运算，对于任意有理数$a$，$b$，都有$a \odot b=10...   
351                       如果$m$，$n$互为相反数，则$m+n=$____$.$   
357   用“$ \spadesuit $”定义新运算，对于任意有理数$a$，$b$，都有$a \sp...   
360                         下列用科学记数法表示的数，正确的是$(\:\:\:)$   
367                       如果$p$，$q$互为相反数，则$p+q=$____$.$   
381   某学校对初一男生进行立定跳远的测试， 以能跳$1.65\text{m}$及以上为达标 ，超过...   
396   某学校对初一男生进行引体向上的测试， 以能做$7$个为标准 ，超过的次数用正数表示，不足的用...   
407   已知$a$，$b$表示有理数，定义运算：“$ \diamondsuit $”，$a \dia...   
416   计算：$|-2 \frac{3}{4} | \times |-2 \frac{2}{15} ...   
...                                                 ...   
6980       式子$3-|n+2|$的最____值是$3$，此时$n=$____.$(\:\:\:)$   
6981       式子$5-|a+1|$的最____值是$5$，此时$a=$____.$(\:\:\:)$   
6982       式子$6-|c-5|$的最____值是$6$，此时$c=$____.$(\:\:\:)$   
6983       式子$2-|m+5|$的最____值是$2$，此时$m=$____.$(\:\:\:)$   
6984   已知：$|x-1|+|y-3|=0$，则$x=$____，$y=$____.$(\:\:\:)$   
6985   已知：$|x-4|+|y+2|=0$，则$x=$____，$y=$____.$(\:\:\:)$   
6986  已知：$|2a-2|+|b-1|=0$，则$a=$____，$b=$____.$(\:\:\:)$   
6987           若$2|x-1|+|3y-6|+2|z-5|=0$，则$x+y+z=$____.   
6988         若$3|2a-4|+4|b-6|+7|5c-5|=0$，则$a+b+c=$____.   
6990    已知$|-m+5|$与$|17-n|$互为相反数，则$m$____$n$.$(\:\:\:)$   
6991      已知$|a+2|$与$|5-b|$互为相反数，则$a$____$b$.$(\:\:\:)$   
6992     已知$|2a-4|$与$|7-b|$互为相反数，则$a$____$b$.$(\:\:\:)$   
6993    已知$|-m+11|$与$|2-n|$互为相反数，则$m$____$n$.$(\:\:\:)$   
6994                      $|m|=2$，其中$m=$____.$(\:\:\:)$   
7009          当$x<0$时，$ \frac{|x|}{x} =$____.$(\:\:\:)$   
7019               计算$-8+(-0.8)+(- \frac{4}{5} )=$____.   
7024  下列各组判断中，正确的是$(\:\:\:)$  ①若$|x|>|y|$，则一定有$x>y$ ...   
7025  下列各组判断中，正确的是$(\:\:\:)$  ①若$|x|=|y|$，则一定有$x=y$或...   
7026  下列各组判断中，正确的是$(\:\:\:)$  ①若$|a|=b$，则一定有$a=b$   ...   
7027  下列各组判断中，正确的是$(\:\:\:)$  ①若$|m|=|n|$，则一定有$m=n$ ...   
7028  下列各组判断中，正确的是$(\:\:\:)$  ①若$|a|<|b|$，则一定有$a<b$ ...   
7029                       已知$|x-1|=3$，则$x$的值为$4$或____.   
7030                       已知$|x-4|=2$，则$x$的值为$6$或____.   
7031                       已知$|m-3|=1$，则$m$的值为$4$或____.   
7032  已知：$a$、$b$都是非$0$有理数，且满足$|ab|=-ab$，则$ \frac{a}{...   
7033  已知：$a$、$b$都是非$0$有理数，且满足$a+b=0$，则$ \frac{a}{|a|...   
7034  已知：$a$、$b$都是非$0$有理数，且满足$|ab|=-ab$，则$ \frac{a}{...   
7035  已知：$a$、$b$都是非$0$有理数，且满足$a+b=0$，则$ \frac{|a|}{a...   
7036  已知：$a$、$b$都是非$0$有理数，且满足$a+b=0$，则$ \frac{a}{|a|...   
7037           计算$(- \frac{1}{8} )+(-3.375)+(-2)=$____.   

                                               explains  \
1     {"{\"body\": \"$-3.782$符号为负,是负数 \\n又是有限小数,是有理数...   
19    {"{\"body\": \"“超过”与“不足”是以每月生产$180$个零件为准 \\n$ ...   
47    {"{\"body\": \"有理数除法法则可以表示成：$p \\\\div q=p \\\...   
56    {"{\"body\": \"$ \\\\because $新运算的规则是：$P \\\\t...   
73    {"{\"body\": \"$\\\\:\\\\:\\\\:\\\\:-3.6+(- \\...   
105   {"{\"body\": \"$ \\\\because |a|

In [63]:
ppp = yls_df.sort_values(by='subsection')

In [65]:
ppp

body  \
1914  有一列数依次为：$ \frac{4}{9}$、$ \frac{12}{11}$、$ \fra...   
5579  仔细观察下面的图案：$\star \perp \circ \#  \ast \star  \...   
2549  如图，$OA$、$OB$、$OC$、$OD$、$OE$是平面内有公共端点的五条射线，从射线$...   
4643  有一列数依次为：$2$、$10$、$50$、$250 \cdots $请根据规律写出该列数的...   
4615  有一列数依次为：$2$、$6$、$18$、$54$、$162 \cdots $请根据规律写出...   
3252  有一列数：$2$，$7$，$13$，$20$，$x$，$37$，$\cdots\cdots$...   
4612  有一列数依次为：$90$、$87$、$84$、$81$、$78 \cdots $请根据规律写...   
1210             下边各图形之间都有相同的规律.    根据这种规律， $m$的值是____.   
1187  如图，$OA$、$OB$、$OC$、$OD$、$OE$是平面内有公共端点的五条射线，从射线$...   
4448                       数表如下图，则第$6$行第$8$列的数是____       
3185  观察下列一组数的排列：$1$，$2$，$3$，$4$，$5$，$4$，$3$，$2$，$1$...   
3183                       数表如下图，则第$1$行第$9$列的数是____       
3180                      数表如下图，则第$1$行第$10$列的数是____       
4835  有一列数依次为$ \frac{1}{3} $、$ \frac{3}{10} $、 $ \fr...   
3176  天鹅座第$61$颗暗星距离地球约$102\:000\:000\:000\:000$千米，如果...   
3172  用科学记数法把$16\:000$写成$a \times 10^n$，其中$a$是____，$...   
3171                        下列用科学记数法表示的数，正确的是$(\:\:\:)$   
4595  有一列数依次为：$3$、$9$、$15$、$21$、$27 \cdots $请根据规律写出该...   
1864  有一列数依次为：$ \frac{1}{2}$、$ \frac{5}{8}$、$ \frac{...   
4490                      数表如下图，则第$7$行第$11$列的数是____       
5547  有一列数依次为：$42$、$37$、$32$、$27$、$22 \cdots $请根据规律写...   
4485                      数表如下图，则第$4$行第$10$列的数是____       
3135          我国人口总数约为$13.68$亿，用科学记数法表示这个数应该是$(\:\:\:)$   
5607  如图，$OA$、$OB$、$OC$、$OD$、$OE$是平面内有公共端点的五条射线，从射线$...   
5598  有一串运算符，依次为：$+- \times - \div -+- \times - \div...   
5594  仔细观察下面的图案：$ \because  \perp  \therefore // \be...   
5593  观察下列一组数的排列：$1$，$2$，$3$，$4$，$5$，$4$，$3$，$2$，$1$...   
3175  下列说法正确的是$(\:\:\:)$ ①数列$2$，$5$，$8$，$11$，$14$，$ ...   
4847                       数表如下图，则第$5$行第$9$列的数是____       
5549  有一列数：$2$，$ 4$，$ 8$， $16$， $x$，$64$，$ \cdots$按规...   
...                                                 ...   
3803                        式子$|2x-1|+2$取最小值时，$x=$____.   
6441                 已知$|m-9|=9-m$，则$m$的取值范围是$(\:\:\:)$   
6438                 已知$|x-8|=8-x$，则$x$的取值范围是$(\:\:\:)$   
645   已知非零有理数$a$，$b$，$c$，化简$\frac{a}{|a|} +\frac{|b|...   
6531                          已知$|x|>x$，则$x$是$(\:\:\:)$   
558                      一个数的绝对值等于数轴上表示这个数的点$(\:\:\:)$.   
521           一个数的绝对值是多少，等于数轴上表示这个数的点____是多少.$(\:\:\:)$   
6356                           $|- \frac{3}{4} |=$____.   
6442                 已知$|m-7|=7-m$，则$m$的取值范围是$(\:\:\:)$   
3204  下列说法中正确的有$(\:\:\:)$ ①正数的绝对值是它本身 ②负数的绝对值是它的相反数 ...   
6748  已知整数$n$的绝对值小于$6$，则$n$的最大值是____，最小值是____.$(\:\:...   
6746  已知整数$m$的绝对值小于$5$，则$m$的最大值是____，最小值是____.$(\:\:...   
5248                   已知$a<2$，则$|2-a|=$____.$(\:\:\:)$   
7036  已知：$a$、$b$都是非$0$有理数，且满足$a+b=0$，则$ \frac{a}{|a|...   
5261                   已知$n>3$，则$|n-3|=$____.$(\:\:\:)$   
6455                 已知$|x-2|=2-x$，则$x$的取值范围是$(\:\:\:)$   
6454                 已知$|a-5|=5-a$，则$a$的取值范围是$(\:\:\:)$   
3898  已知：有理数$m$、$n$在数轴上的位置如图所示，则化简$|m+n|$的结果为$(\:\:\...   
3839  已知：有理数$a$、$b$在数轴上的位置如图所示，则化简$|a+b|$的结果为$(\:\:\...   
6747  已知整数$a$的绝对值小于$4$，则$a$的最大值是____，最小值是____.$(\:\:...   
6700       已知：$|m|=4$，$|n|=1$，且$m<n$，则$m$的值等于$(\:\:\:)$   
6734  已知：有理数$b$在数轴上的位置如图所示，则化简$|b-1|$的结果为$(\:\:\:)$       
6735  已知：有理数$b$在数轴上的位置如图所示，则化简$|-b+1|$的结果为$(\:\:\:)$...   
6738            已知整数$n$的绝对值大于$2$小于$5$，则符合条件的$n$共有____个.   
6739            已知整数$m$的绝对值大于$1$小于$4$，则符合条件的$m$共有____个.   
6740            已知整数$p$的绝对值大于$2$小于$8$，则符合条件的$p$共有____个.   
6741            已知整数$a$的绝对值大于$3$小于$7$，则符合条件的$a$共有____个.   
6742            已知整数$q$的绝对值大于$2$小于$6$，则符合条件的$q$共有____个.   
6703       已知：$|p|=5$，$|q|=2$，且$p<q$，则$p$的值等于$(\:\:\:)$   
3688  $|9|=$____，$|-9|=$____，互为相反数的两个数，它们的绝对值____$(\...   

                                               explains  \
1914  {"{\"body\": \"仔细观察，分子的排列符合等比数列的规律，第$6$个数的分子为$...   
5579  {"{\"body\": \"该组图案每$5$个就重复一次 \\n第$1$个$\\\\cir...   
2549  {"{\"body\": \"由图可知，周期为$5$. \\n$424 \\\\div 5=...   
4643  {"{\"body\": \"分析思路：根据相邻两个数的比不变，可以找出每一个数跟第$1$个...   
4615  {"{\"body\": \"分析思路：根据相邻两个数的比不变，可以找出每一个数跟第$1$个...   
3252  {"{\"body\": \"$2+\\\\textcolor{

In [66]:
ppp.subsection.unique()

array(['', '乘方', '数轴', '有理数', '有理数的乘法', '有理数的减法', '有理数的加法', '有理数的除法',
       '正数和负数', '相反数', '绝对值'], dtype=object)

In [138]:
from gensim.test.utils import common_texts
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(common_texts)]
model = Doc2Vec(documents, vector_size=5, window=2, min_count=1, workers=4)

In [81]:
common_texts

[['human', 'interface', 'computer'],
 ['survey', 'user', 'computer', 'system', 'response', 'time'],
 ['eps', 'user', 'interface', 'system'],
 ['system', 'human', 'system', 'eps'],
 ['user', 'response', 'time'],
 ['trees'],
 ['graph', 'trees'],
 ['graph', 'minors', 'trees'],
 ['graph', 'minors', 'survey']]

In [82]:
documents

[TaggedDocument(words=['human', 'interface', 'computer'], tags=[0]),
 TaggedDocument(words=['survey', 'user', 'computer', 'system', 'response', 'time'], tags=[1]),
 TaggedDocument(words=['eps', 'user', 'interface', 'system'], tags=[2]),
 TaggedDocument(words=['system', 'human', 'system', 'eps'], tags=[3]),
 TaggedDocument(words=['user', 'response', 'time'], tags=[4]),
 TaggedDocument(words=['trees'], tags=[5]),
 TaggedDocument(words=['graph', 'trees'], tags=[6]),
 TaggedDocument(words=['graph', 'minors', 'trees'], tags=[7]),
 TaggedDocument(words=['graph', 'minors', 'survey'], tags=[8])]

In [83]:
vector = model.infer_vector(["system", "response"])

In [84]:
vector

array([-0.01519612,  0.08389594, -0.02690305,  0.09432001,  0.05190121],
      dtype=float32)

In [93]:
sss = 'human interface computer'

In [124]:
model.vocabulary

In [110]:
for i in range(9):
    print(model.docvecs[i])

[ 0.01957394 -0.04352891  0.01151429 -0.07564452 -0.09589833]
[-0.04559866  0.07477349  0.01417593 -0.07347184  0.02556597]
[ 0.05713726 -0.09597804  0.03329236  0.01998447 -0.05379698]
[ 0.0928795  -0.02861902  0.01968862 -0.05019694  0.05132913]
[-0.02776747  0.08597849  0.09722327 -0.05988003  0.0174726 ]
[ 0.00773704  0.04519016 -0.01517135 -0.0546782   0.05898836]
[ 0.08909235 -0.02025969  0.06551914  0.02119997 -0.02918315]
[-0.06155676  0.08868406 -0.07165428 -0.07436979  0.09846402]
[0.01515704 0.06550371 0.06401108 0.04028419 0.00267623]


In [115]:
model.docvecs.distance(0,3)

0.8656472563743591

In [133]:
model.docvecs.most_similar(1)

[(4, 0.8043986558914185),
 (7, 0.776969850063324),
 (5, 0.7530813217163086),
 (8, 0.1860945224761963),
 (0, -0.056532710790634155),
 (3, -0.07584896683692932),
 (6, -0.4990019202232361),
 (2, -0.7928260564804077)]

In [136]:
res = []
for i in range(9):
    res.append((i,model.docvecs.distance(1,i)))
sorted(res,key=lambda x:x[1])

[(1, 0.0),
 (4, 0.19560134410858154),
 (7, 0.22303014993667603),
 (5, 0.2469186782836914),
 (8, 0.8139055222272873),
 (0, 1.056532770395279),
 (3, 1.0758489966392517),
 (6, 1.499001920223236),
 (2, 1.7928260564804077)]

In [128]:
model.docvecs.closer_than(1,2)

KeyError: 1

In [131]:
model.docvecs.similarity(1,2),model.docvecs.distance(1,2)

(-0.79282606, 1.7928260564804077)

In [132]:
model.docvecs.similarity(1,3),model.docvecs.distance(1,3)

(-0.075849, 1.0758489966392517)

In [142]:
14824+30000-1450

43374

In [143]:
841**2

707281